const CATEGORY = [
  {
    category_id: 1,
    subCategory_id: 1,
    main_name: '구독하기',
    sub_name: '구독하기',
    img: 'subscribe.png',
    imgW: 'subscribeW.png',
  },
  {
    category_id: 3,
    subCategory_id: 5,
    main_name: '중고등 참고서',
    sub_name: '고등참고서',
    img: 'highschool.png',
    imgW: 'highschoolW.png',
  },
  {
    category_id: 3,
    subCategory_id: 4,
    main_name: '중고등 참고서',
    sub_name: '중등참고서',
    img: 'middleschool.png',
    imgW: 'middleschoolW.png',
  },
  {
    category_id: 4,
    subCategory_id: 6,
    main_name: '취업/수험생',
    sub_name: '어학',
    img: 'language.png',
    imgW: 'languageW.png',
  },
  {
    category_id: 4,
    subCategory_id: 7,
    main_name: '취업/수험생',
    sub_name: '인적성/직무능력',
    img: 'test.png',
    imgW: 'testW.png',
  },
  {
    category_id: 2,
    subCategory_id: 2,
    main_name: '자기 계발',
    sub_name: '성공/처세',
    img: 'success.png',
    imgW: 'successW.png',
  },
  {
    category_id: 2,
    subCategory_id: 3,
    main_name: '자기 계발',
    sub_name: '인간관계',
    img: 'peoples.png',
    imgW: 'peoplesW.png',
  },
];

export default CATEGORY;
